spring:
  cloud:
    gateway:
      routes:
        - id: hello-world-service
          uri: http://localhost:8089
          predicates:
            - Path=/api/hello-world/**
          filters:
            - StripPrefix=1

        - id: dept-service
          uri: http://localhost:8090
          predicates:
            - Path=/api/dept/**
          filters:
            - StripPrefix=1

        - id: auth-service
          uri: http://localhost:8050
          predicates:
            - Path=/api/auth/login
          filters:
            - StripPrefix=1
